### ISSUE TITLE
Runtime error 0xc000007b after compiling example in VC++2012

### ISSUE THREAD

**Issue by orange456** [OpenCVBlobsLib/opencvblobslib#17]
I was able to install pthreadswin32 and get the build to go OK in Cmake.  The compile and linking of the built solution also goes ok, but when I try to run the example executable, either directly or debugging in VC++, I get this error.  Would someone be able to offer some advice?

Is this possibly a x64 vs x32 issue?  I'm running Windows 8.1 (64-bit).

**Comment by bloodbaby** [comment]
I normally use release mode with win32 platform,and compiling is successful.
I compile all with VS solutions (not Cmake cos unix is not my concern).
Remember to have lib and dll at the same time and do not forget the tbb.dll in the sln's  Release filefolder （A screenshot is attached）
![lib&dll in Release filefolder](http://img.blog.csdn.net/20150531141756059)
Add following two lines before the main function
\#include "stdfax.h" 
\#include "global.h"
based on the following three Head file attached in your project.
After all these step you can use freely without changing “Project Properties”
1、targetver.h

```C++
#pragma once
#include <SDKDDKVer.h>
```



2、stdfax.h

```C++
#pragma once

#include "targetver.h"

#include <stdio.h>
#include <tchar.h>
```

3、global.h

```C++
#ifndef GLOBAL_H
#define GLOBAL_H


#include "opencv/cv.h"
#include "opencv2/opencv.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <omp.h>
#include "pthreads/pthread.h"
#include "pthreads/sched.h"
#include "pthreads/semaphore.h"

//using Release mode win32 platform lib
#pragma comment(lib,"..\\Release\\opencv_calib3d231.lib")
#pragma comment(lib,"..\\Release\\opencv_contrib231.lib")
#pragma comment(lib,"..\\Release\\opencv_core231.lib")
#pragma comment(lib,"..\\Release\\opencv_features2d231.lib")
#pragma comment(lib,"..\\Release\\opencv_flann231.lib")
#pragma comment(lib,"..\\Release\\opencv_gpu231.lib")
#pragma comment(lib,"..\\Release\\opencv_haartraining_engine.lib")
#pragma comment(lib,"..\\Release\\opencv_highgui231.lib")
#pragma comment(lib,"..\\Release\\opencv_imgproc231.lib")
#pragma comment(lib,"..\\Release\\opencv_legacy231.lib")
#pragma comment(lib,"..\\Release\\opencv_ml231.lib")
#pragma comment(lib,"..\\Release\\opencv_objdetect231.lib")
#pragma comment(lib,"..\\Release\\opencv_ts231.lib")
#pragma comment(lib,"..\\Release\\opencv_video231.lib")
#pragma comment(lib,"..\\Release\\pthreadVC2.lib")
#pragma comment(lib,"..\\Release\\pthreadVCE2.lib")
#pragma comment(lib,"..\\Release\\pthreadVSE2.lib")


using namespace std;
using namespace cv;
#endif
```
