### ISSUE TITLE
Installation on linux / Cmake

### ISSUE THREAD

**Issue by dilbie** [OpenCVBlobsLib/opencvblobslib#6]
Hi
I am using linux and have just updated from cvblob (https://code.google.com/p/cvblob/) and after building opencvblobslib I had to manually install the files in directories that seemed appropriate based on where the cvblob files were. I also manually created a opencvblobslibConfig.cmake file as the project I am working on uses cmake to build which requires the presence of this file to properly find the required include paths.

If cmake could be used to build opencvblobslib this file could automatically be made as well as customising the makefile to allow 'make install' to automatically install the files in the required locations, which would be a huge help. If using cmake is not possible I was wondering if at the very least there was any chance of adding an install option to the makefile to allow easier updating when new versions of opencvblobslib are released.
Thanks

**Comment by BenElias** [comment]
hi

i am new with ubuntu 
how could i install & complie opencvblobslib  
thx
